In [1]:
import numpy as np

In [2]:
L = list(range(10))
print(L)
LL = [l**2 for l in L]
print(LL)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [3]:
A = np.arange(10)
print(A)
AA = A**2
print(AA)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [4]:
L = list(range(1000))
%timeit [l**2 for l in L]

243 µs ± 13.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
A = np.arange(1000)
%timeit A**2

683 ns ± 27.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.eye(1)

array([[1.]])

In [9]:
np.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [10]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [11]:
np.eye(10, 6,)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.eye(3, 1)

array([[1.],
       [0.],
       [0.]])

In [13]:
np.eye(1, 3)

array([[1., 0., 0.]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.zeros((10, 10)).dtype

dtype('float64')

In [18]:
np.array([1+1j, -3+4j])

array([ 1.+1.j, -3.+4.j])

In [19]:
np.array([1+1j, -3+4j]).dtype

dtype('complex128')

In [20]:
np.array(["Saif", "Sameer", "Shamshu"])

array(['Saif', 'Sameer', 'Shamshu'], dtype='<U7')

In [21]:
print(np.array(["Saif", "Sameer", "Shamshu"]).dtype)

<U7


In [22]:
lst = list(range(10))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
lst[5:] = [100, 101, 102, 104, 100, 100, 100, 100, 100, 100]
lst

[0, 1, 2, 3, 4, 100, 101, 102, 104, 100, 100, 100, 100, 100, 100]

In [24]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr[5:] = 100
arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [26]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [28]:
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [29]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a[5:] = 5

In [31]:
a

array([0, 1, 2, 3, 4, 5, 5, 5, 5, 5])

In [32]:
a = np.arange(3)

In [33]:
a

array([0, 1, 2])

In [34]:
for i in a:
    print(i, id(i))

0 139677914142256
1 139677914142960
2 139677914142256


In [35]:
b = a[::-1]

In [36]:
b

array([2, 1, 0])

In [37]:
for j in b:
    print(j, id(j))

2 139677914143120
1 139677914143344
0 139677914143120


In [38]:
np.shares_memory(a, b)

True

In [39]:
b[0] = 11

In [40]:
a

array([ 0,  1, 11])

In [41]:
b

array([11,  1,  0])

In [42]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [43]:
for ele in arr:
    print(ele, id(ele))

0 139677914144048
1 139677914143408
2 139677914144048
3 139677914143408
4 139677914144048


In [44]:
x1, x2, x3, x4, x5 = arr

In [45]:
id(x1), id(x2), id(x3), id(x4), id(x5)

(139677914144144,
 139677914143856,
 139677914144080,
 139677914144304,
 139677914144240)

In [46]:
for ele in arr:
    print(ele, id(ele))

0 139677914143632
1 139677914144048
2 139677914143632
3 139677914144048
4 139677914143632


In [47]:
[id(x) for x in arr.tolist()]

[139678735745232,
 139678735745264,
 139678735745296,
 139678735745328,
 139678735745360]

In [48]:
arrlst = np.random.randint(low=10, high=100, size=25)
arrlst

array([98, 59, 96, 48, 51, 89, 65, 26, 37, 58, 72, 22, 75, 15, 21, 15, 18,
       89, 65, 15, 17, 36, 66, 51, 91])

In [49]:
mask = (arrlst % 2 == 0)
mask

array([ True, False,  True,  True, False, False, False,  True, False,
        True,  True,  True, False, False, False, False,  True, False,
       False, False, False,  True,  True, False, False])

In [50]:
ext_arrlst = arrlst[mask]
ext_arrlst

array([98, 96, 48, 26, 58, 72, 22, 18, 36, 66])

In [51]:
np.shares_memory(arrlst, ext_arrlst)

False

In [52]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [53]:
arr + 1

array([2, 3, 4])

In [54]:
np.shares_memory(arr, arr+1)

False

In [55]:
U = np.ones((3, 3), dtype=int)
print(U)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [56]:
U_mul = U.dot(U)
print(U_mul)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [57]:
U.all()

True

In [58]:
U_mul.all()

True

In [59]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

In [60]:
data = np.loadtxt(fname="populations.txt")

In [61]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [62]:
data.T

array([[ 1900.,  1901.,  1902.,  1903.,  1904.,  1905.,  1906.,  1907.,
         1908.,  1909.,  1910.,  1911.,  1912.,  1913.,  1914.,  1915.,
         1916.,  1917.,  1918.,  1919.,  1920.],
       [30000., 47200., 70200., 77400., 36300., 20600., 18100., 21400.,
        22000., 25400., 27100., 40300., 57000., 76600., 52300., 19500.,
        11200.,  7600., 14600., 16200., 24700.],
       [ 4000.,  6100.,  9800., 35200., 59400., 41700., 19000., 13000.,
         8300.,  9100.,  7400.,  8000., 12300., 19500., 45700., 51100.,
        29700., 15800.,  9700., 10100.,  8600.],
       [48300., 48200., 41500., 38200., 40600., 39800., 38600., 42300.,
        44500., 42100., 46000., 46800., 43800., 40900., 39400., 39000.,
        36700., 41800., 43300., 41300., 47300.]])

In [63]:
year, hare, lynx, carrot = data.T

In [64]:
year

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [65]:
hare

array([30000., 47200., 70200., 77400., 36300., 20600., 18100., 21400.,
       22000., 25400., 27100., 40300., 57000., 76600., 52300., 19500.,
       11200.,  7600., 14600., 16200., 24700.])

In [66]:
lynx

array([ 4000.,  6100.,  9800., 35200., 59400., 41700., 19000., 13000.,
        8300.,  9100.,  7400.,  8000., 12300., 19500., 45700., 51100.,
       29700., 15800.,  9700., 10100.,  8600.])

In [67]:
carrot

array([48300., 48200., 41500., 38200., 40600., 39800., 38600., 42300.,
       44500., 42100., 46000., 46800., 43800., 40900., 39400., 39000.,
       36700., 41800., 43300., 41300., 47300.])

In [68]:
populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [69]:
# Which specie is more across all the years?
populations.argmax(axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

In [70]:
# Which specie is less across all the years?
populations.argmin(axis=1)

array([1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 1, 1, 1])

In [71]:
populations.argmax(axis=0)

array([3, 4, 0])

In [72]:
populations.mean(axis=0)

array([34080.95238095, 20166.66666667, 42400.        ])

In [73]:
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [74]:
arr1 = np.array([0, 10, 20, 30]).reshape((4, 1))

In [75]:
arr1

array([[ 0],
       [10],
       [20],
       [30]])

In [76]:
arr2 = np.array([0, 1, 2]).reshape((1, 3))
arr2

array([[0, 1, 2]])

In [77]:
arr1 + arr2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [78]:
arr1 * arr2

array([[ 0,  0,  0],
       [ 0, 10, 20],
       [ 0, 20, 40],
       [ 0, 30, 60]])

In [79]:
arr1.dot(arr2)

array([[ 0,  0,  0],
       [ 0, 10, 20],
       [ 0, 20, 40],
       [ 0, 30, 60]])

In [80]:
np.matmul(arr1, arr2)

array([[ 0,  0,  0],
       [ 0, 10, 20],
       [ 0, 20, 40],
       [ 0, 30, 60]])

In [81]:
arr = np.array([[5, 4, 6], [2, 3, 2]])
arr

array([[5, 4, 6],
       [2, 3, 2]])

In [82]:
arr.sort(axis=1)
arr

array([[4, 5, 6],
       [2, 2, 3]])

In [83]:
arr = np.array([[5, 4, 6], [2, 3, 2]])
arr

array([[5, 4, 6],
       [2, 3, 2]])

In [84]:
arr.sort(axis=0)
arr

array([[2, 3, 2],
       [5, 4, 6]])

In [85]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [86]:
arr.resize((8, 2), refcheck=False)

In [87]:
arr

array([[1, 2],
       [3, 4],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [88]:
arr.resize((4,), refcheck=False)

In [89]:
arr

array([1, 2, 3, 4])