Link: https://youtu.be/nNDqbUhtIRg

Paper: https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tagging-1.pdf

![](https://user-images.githubusercontent.com/63338657/185819867-c87a1e1e-4e52-4156-b711-84aa347945b0.png)

![](https://user-images.githubusercontent.com/63338657/185820535-06449d7e-7ec5-4c48-837c-cfa8eaf4619b.png)

![](https://user-images.githubusercontent.com/63338657/185820921-0547161c-86d5-4a55-83d5-4ace6c71a726.png)

![](https://user-images.githubusercontent.com/63338657/185821098-00600c05-c638-4f41-b80b-0f22cef3e401.png)

![](https://user-images.githubusercontent.com/63338657/185821557-d6aba4c0-128a-4cf5-b68c-211489bafb89.png)

Important Link: https://scikit-learn.org/stable/modules/multiclass.html

![](https://user-images.githubusercontent.com/63338657/186036806-e19f5805-4a97-4cab-a772-7714ad85f8da.png)

![](https://user-images.githubusercontent.com/63338657/186037330-9ede6240-7250-48c6-ab7f-e06f52186a0b.png)

![](https://user-images.githubusercontent.com/63338657/186037803-141cc3a0-0cf4-4c91-ba0f-370c5280e4e1.png)

![](https://user-images.githubusercontent.com/63338657/186037968-8a92899d-fe57-472f-bd79-a1e6091ce2ad.png)

![](https://user-images.githubusercontent.com/63338657/186038214-dc798301-54b4-4743-a9a2-24ab60b55fda.png)

![](https://user-images.githubusercontent.com/63338657/186038331-5a60f9b5-5559-4092-83a3-ad76e8bac4de.png)

![](https://user-images.githubusercontent.com/63338657/186038714-a37de6f6-1d4d-482c-8d35-03c0b5acef46.png)

![](https://user-images.githubusercontent.com/63338657/186039089-b029f983-ca11-425f-8164-fd8e9de1dbe5.png)

![](https://user-images.githubusercontent.com/63338657/186039427-2a9e8f0e-765f-4d36-b3f5-b968d15250e4.png)

![](https://user-images.githubusercontent.com/63338657/186039580-809181d8-4900-4b43-b5b9-a2ada6b3bd69.png)

![](https://user-images.githubusercontent.com/63338657/186039729-5fb45f36-f654-4863-863c-5606cce7e4ce.png)

![](https://user-images.githubusercontent.com/63338657/186545687-48a0c50e-4b8b-4095-a1e5-63fe3c2ab4ef.png)

![](https://user-images.githubusercontent.com/63338657/186545769-8fcbcbcc-0c16-42ce-af15-f953611344cb.png)

Link: https://www.analyticsvidhya.com/blog/2017/08/introduction-to-multi-label-classification/

![](https://user-images.githubusercontent.com/63338657/186547358-ca33d8cf-da39-4f86-8caf-15d38c4e4122.png)

Link: https://aoakintibu.medium.com/multilabel-classification-with-cnn-278702d98c5b

![](https://user-images.githubusercontent.com/63338657/186938954-4c1ba77a-1638-4b73-9e49-057b9966a702.png)

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np

In [3]:
arr1 = np.matrix([[1, 2, 3, 4], [1, 2, 3, 4]])
print(arr1)
print(arr1.sum(axis=0))
print(arr1.sum(axis=1))

[[1 2 3 4]
 [1 2 3 4]]
[[2 4 6 8]]
[[10]
 [10]]


In [4]:
arr2 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
print(arr2)
print(arr2.sum(axis=0))
print(arr2.sum(axis=1))

[[1 2 3 4]
 [1 2 3 4]]
[2 4 6 8]
[10 10]


In [5]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


In [6]:
print(type(X))

<class 'scipy.sparse._csr.csr_matrix'>


In [7]:
print(X.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [8]:
from IPython.display import display

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(data={'C1': [[1], [2], [3], [4]],
                        'C2': [[1], [2], [3], [4]]})
display(df)

C1   C2
0  [1]  [1]
1  [2]  [2]
2  [3]  [3]
3  [4]  [4]

In [11]:
display(df.sum())
display(df.sum(axis=0))
display(df.sum(axis=1))

C1    [1, 2, 3, 4]
C2    [1, 2, 3, 4]
dtype: object

C1    [1, 2, 3, 4]
C2    [1, 2, 3, 4]
dtype: object

0    [1, 1]
1    [2, 2]
2    [3, 3]
3    [4, 4]
dtype: object

In [12]:
display(df.sum().sum())
display(df.sum(axis=0).sum())
display(df.sum(axis=1).sum())

[1, 2, 3, 4, 1, 2, 3, 4]

[1, 2, 3, 4, 1, 2, 3, 4]

[1, 1, 2, 2, 3, 3, 4, 4]

In [13]:
from sklearn.metrics import confusion_matrix

In [14]:
cmat = confusion_matrix(y_true=[1, 2, 3, 4, 5], y_pred=[1, 1, 3, 2, 5])
print(type(cmat))
print(cmat)

<class 'numpy.ndarray'>
[[1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 0 0 1]]


In [15]:
print(cmat / cmat.sum(axis=0))
print(((cmat.T) / (cmat.sum(axis=1).T)).T)

[[0.5 0.  0.  nan 0. ]
 [0.5 0.  0.  nan 0. ]
 [0.  0.  1.  nan 0. ]
 [0.  1.  0.  nan 0. ]
 [0.  0.  0.  nan 1. ]]
[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
t = [2, 4, 6, 8]
t_sorted = sorted(range(len(t)), key=lambda i: t[i], reverse=True)
print(t_sorted)

[3, 2, 1, 0]


![](https://user-images.githubusercontent.com/63338657/186948276-72170d4d-c46b-45de-b462-beb84c61a487.png)

![](https://user-images.githubusercontent.com/63338657/186953307-7316201b-c09c-4e20-bd6b-627186d33b8f.png)

![](https://user-images.githubusercontent.com/63338657/186956636-e3f50fef-5d41-41ec-82df-d27650e2561b.png)